on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NETWORK_OPTION: "--network ${{ job.container.network }}"

jobs:
  taqueria-init-job:
    runs-on: ubuntu-latest
    name: Initialize a taqueria project
    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.x

      - name: taq init step
        uses: ./
        with:
          task: 'init'
          
      - name: install ligo plugin
        uses: ./
        with:
          task: install @taqueria/plugin-ligo

      - name: install flextesa plugin
        uses: ./
        with:
          task: install @taqueria/plugin-flextesa@0.0.0-pr-741-86f0b45e

      - name: install taquito plugin
        uses: ./
        with:
          task: install @taqueria/plugin-taquito@0.0.0-pr-741-86f0b45e

      - name: compile the contracts
        uses: ./
        with:
          task: 'compile'

      - name: start local sandbox
        uses: ./
        with:
          task: 'start sandbox local'

      - name: list accounts
        uses: ./
        with:
          task: 'list accounts local'

      # - name: package artifacts
      #   run: zip -r artifacts.zip ./test-project/artifacts/*

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./artifacts/*
          retention-days: 1

      - name: originate the contract
        uses: ./
        with:
          task: 'originate'