on: [push]

concurrency:
  group: ${{ github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  taqueria-init-job:
    runs-on: ubuntu-latest
    name: Initialize a taqueria project
    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.x

      - name: taq init step
        uses: ./
        with:
          project_name: 'test-project'
          task: 'init'

      - name: copy contract
        run: |
          sudo cp contracts/counter.jsligo test-project/contracts/
          
      - name: install all the plugins
        uses: ./
        with:
          project_name: 'test-project'
          task: >-
              install 
              @taqueria/plugin-ligo@0.0.0-pr-704-edcf22c3
              @taqueria/plugin-smartpy@0.0.0-pr-704-edcf22c3
              @taqueria/plugin-taquito@0.0.0-pr-704-edcf22c3
              @taqueria/plugin-flextesa@0.0.0-pr-704-edcf22c3
              @taqueria/plugin-contract-types@0.0.0-pr-704-edcf22c3
              @taqueria/plugin-archetype@0.0.0-pr-704-edcf22c3
              @taqueria/plugin-tezos-client@0.0.0-pr-704-edcf22c3

      - name: compile the contracts
        uses: ./
        with:
          project_name: 'test-project'
          task: 'compile'

      - name: package artifacts
        run: zip -r artifacts.zip ./test-project/artifacts/*

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts.zip
          path: artifacts.zip
          retention-days: 1