on: [push]

jobs:
  taqueria-init-job:
    runs-on: ubuntu-latest
    name: Initialize a taqueria project
    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.x

      - name: taq init step
        uses: ./
        with:
          project_name: 'test-project'
          task: 'init'

      - name: copy contract
        run: |
          sudo cp contracts/counter.jsligo test-project/contracts/
          
      - name: install the ligo plugin
        uses: ./
        with:
          project_name: 'test-project'
          task: 'install @taqueria/plugin-ligo@0.0.0-pr-704-edcf22c3'

      - name: compile the contracts
        uses: ./
        with:
          project_name: 'test-project'
          task: 'compile'