on: [push]

concurrency:
  group: ${{ github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  taqueria-init-job:
    runs-on: ubuntu-latest
    name: Initialize a taqueria project
    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.x

      - name: taq init step
        uses: ./
        with:
          project_name: 'test-project'
          task: 'init'

      - name: copy contract
        run: |
          sudo cp contracts/counter.jsligo test-project/contracts/
          
      - name: install ligo plugin
        uses: ./
        with:
          project_name: 'test-project'
          task: install @taqueria/plugin-ligo@0.0.0-pr-704-edcf22c3

      - name: install flextesa plugin
        uses: ./
        with:
          project_name: 'test-project'
          task: install @taqueria/plugin-flextesa@0.0.0-pr-741-00ab80d0

      - name: compile the contracts
        uses: ./
        with:
          project_name: 'test-project'
          task: 'compile'

      - name: start local sandbox
        uses: ./
        with:
          project_name: 'test-project'
          task: 'start sandbox local'

      - name: list accounts
        uses: ./
        with:
          project_name: 'test-project'
          task: 'list accounts local'

      # - name: package artifacts
      #   run: zip -r artifacts.zip ./test-project/artifacts/*

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./test-project/artifacts/*
          retention-days: 1